# Project information
site_name: 'Timestrap Docs'
site_description: 'Docs for the Timestrap project.'
site_author: 'Isaac Bythewood'
site_url: 'https://timestrap.bythewood.me/'

# Repository
repo_name: 'overshard/timestrap'
repo_url: 'https://github.com/overshard/timestrap'

# Copyright
copyright: 'Copyright &copy; 2019 Isaac Bythewood'

# Navigation
nav:
  - Home: 'index.md'
  - Screenshots: 'screenshots.md'
  - Configuration: 'configuration.md'
  - Permissions: 'permissions.md'
  - Sites: 'sites.md'
  - Uses: 'uses.md'
  - Docs: 'docs.md'
  - Contributing: 'contributing.md'
  - License: 'license.md'

# Configuration
docs_dir: 'docs/src'
site_dir: 'docs/dist'
edit_uri: 'edit/master/docs/src/'
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
